apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: "2021-06-13T12:44:39Z"
    generation: 1
    labels:
      app: quotesapi
      app.kubernetes.io/component: quotesapi
      app.kubernetes.io/instance: quotesapi
    managedFields:
    - apiVersion: image.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/generated-by: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
      manager: oc
      operation: Update
      time: "2021-06-13T12:44:39Z"
    name: quotesapi
    namespace: jsew-ca-ibm-com-quotes-dev
    resourceVersion: "87251153"
    selfLink: /apis/image.openshift.io/v1/namespaces/jsew-ca-ibm-com-quotes-dev/imagestreams/quotesapi
    uid: 50da9120-6a67-4291-8968-a369a2042394
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: image-registry.openshift-image-registry.svc:5000/jsew-ca-ibm-com-quotes-dev/quotesapi
    publicDockerImageRepository: default-route-openshift-image-registry.apps.na45.prod.nextcle.com/jsew-ca-ibm-com-quotes-dev/quotesapi
    tags:
    - items:
      - created: "2021-06-13T12:45:11Z"
        dockerImageReference: image-registry.openshift-image-registry.svc:5000/jsew-ca-ibm-com-quotes-dev/quotesapi@sha256:2b03c61775f973a179eab06911085a69fd99f24b03cd2bc4723550864c34cac9
        generation: 1
        image: sha256:2b03c61775f973a179eab06911085a69fd99f24b03cd2bc4723550864c34cac9
      tag: latest
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/image.dockerRepositoryCheck: "2021-06-13T12:44:30Z"
    creationTimestamp: "2021-06-13T12:44:30Z"
    generation: 2
    name: quotesdb
    namespace: jsew-ca-ibm-com-quotes-dev
    resourceVersion: "87250817"
    selfLink: /apis/image.openshift.io/v1/namespaces/jsew-ca-ibm-com-quotes-dev/imagestreams/quotesdb
    uid: 1ac15d47-20e4-493e-bcb6-8b27f6365686
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: image-registry.openshift-image-registry.svc:5000/openshift/mysql:5.7
      generation: 2
      importPolicy: {}
      name: "5.7"
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: image-registry.openshift-image-registry.svc:5000/jsew-ca-ibm-com-quotes-dev/quotesdb
    publicDockerImageRepository: default-route-openshift-image-registry.apps.na45.prod.nextcle.com/jsew-ca-ibm-com-quotes-dev/quotesdb
    tags:
    - items:
      - created: "2021-06-13T12:44:30Z"
        dockerImageReference: image-registry.openshift-image-registry.svc:5000/openshift/mysql@sha256:9a781abe7581cc141e14a7e404ec34125b3e89c008b14f4e7b41e094fd3049fe
        generation: 2
        image: sha256:9a781abe7581cc141e14a7e404ec34125b3e89c008b14f4e7b41e094fd3049fe
      tag: "5.7"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
